include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    
analyzer:
  errors:
    prefer_const_constructors: error
    prefer_const_declarations: error
