name: weather_now
description: "Consult Weather Now"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.7
  device_preview: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  husky: ^0.1.6
  lint_staged: ^0.4.2
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

lint_staged:
  'lib/**.dart': dart format -l 120 && dart analyze --fatal-infos --fatal-warnings
