name: weather_now
description: "Consult Weather Now"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
