name: weather_now
description: "Consult Weather Now"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
